### ISSUE TITLE
Can not set mintFee less than 1

### ISSUE THREAD

**Issue by hoanghiep** [FTM-Labs/Aptos-NFT-Mint#10]
My config
```
"collection": {
        "assetDir": "/home/hieptran/Projects/Aptos-NFT-Mint/assets/images",
        "metadataDir": "/home/hieptran/Projects/Aptos-NFT-Mint/assets/metadata",
        "collectionName": "Latte NFT v2",
        "collectionDescription": "Latte NFT v2",
        "collectionCover": "",
        "collectionSize": 9,
        "maxMintPerWallet": 9,
        "mintFee": 0.9,
        "royalty_points_denominator": 1000,
        "royalty_points_numerator": 100,
        "presaleMintTime": 100000000,
        "publicMintTime": 100000000,
        "whitelistDir": "/home/hieptran/Projects/Aptos-NFT-Mint/assets/whitelist"
    }
```

Mint site http://localhost:3000/:
![mint-site-2](https://user-images.githubusercontent.com/1551503/197116799-f2f349f5-01ca-49ff-abf2-d3cdbf2d5e34.PNG)

**Comment by aekiratli** [comment]
Same here with the latest [commit](https://github.com/FTM-Labs/Aptos-NFT-Mint/commit/4a78c73edf5abd45b795c8826669525d106aa1a8)

**Comment by dh1ki** [comment]
i'm facing the same issue here, seems like problem with the candy machine (?)

**Comment by nikola43** [comment]
@hoanghiep You are trying put less than minimum amount, remember 1000000 == 1 APT 
0.9 = 900000
