### ISSUE TITLE
Error: Cannot find module '@solana/web3.js'

### ISSUE THREAD

**Issue by nanashi019** [FTM-Labs/Aptos-NFT-Mint#24]
can't boot mint-site page
when i command "npm run dev"
unhandled error occurs, how can i solve this
any relation with solana web3??? I don't understand

**Comment by aekiratli** [comment]
run `yarn add @solana/web3.js`

**Comment by nanashi019** [comment]
thanx. what is relation with solana web3? I just wonder

**Comment by AptosApe** [comment]
no relation, just need to delete it from dependencies. lol
