### ISSUE TITLE
Error: Cannot find module '@solana/web3.js' Require stack:

### ISSUE THREAD

**Issue by aycanozarpaci** [FTM-Labs/Aptos-NFT-Mint#29]
Hashlips ile görselleri ve json oluşturdum. bundan sonra Github'a aynen aktarmışsınız. Sonuç olarak solana ulaşamayacak mı yardımcı olur musunuz?

![image](https://user-images.githubusercontent.com/44923151/197660003-86445257-5b65-4a51-8951-4f3d799ad476.png)

**Comment by W3TFT** [comment]
`yarn add @solana/web3.js` 
or
`sudo yarn add @solana/web3.js`

**Comment by aycanozarpaci** [comment]
> `yarn add @solana/web3.js` or `sudo yarn add @solana/web3.js`

Thanks Worked ♥
